server:
  port: 8081
  context-path: 
  
security:
  sessions: if-required
  
eureka:
  client:
    service-url: 
      defaultZone: http://192.168.8.102:8084/eureka/
      
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: oauth_service
    